// Generated by CoffeeScript 1.9.2
(function() {
  var VectorEffect, root;

  VectorEffect = cc.ParticleSystem.extend({
    ax: 0,
    ay: 0,
    vx: 0,
    vy: 0,
    ctor: function(battle) {
      this.battle = battle;
      this._super(res.fly_decorate);
      this.setPositionType(cc.ParticleSystem.TYPE_FREE);
      this.battle.addChild(this, 10);
      this.setPosition(400, 225);
      this.t = 0;
      return this.lt = 2;
    },
    initSpeed: function(vx, vy, ax, ay) {
      this.vx = vx;
      this.vy = vy;
      this.ax = ax;
      this.ay = ay;
    },
    update: function(dt) {
      this._super(dt);
      this.t += dt;
      this.setPosition(this.x + this.vx, this.y + this.vy);
      this.vx += this.ax;
      this.vy += this.ay;
      if (this.x < -200 || this.x > gs.size.width + 200 || this.y < -200 || this.y > gs.size.height + 200) {
        this.stopSystem();
      }
      if (this.t > this.lt) {
        this.stopSystem();
      }
      if (this.t > this.lt * 1.5) {
        return this.removeSelf();
      }
    },
    removeSelf: function() {
      this.battle.removeChild(this, true);
      return console.log("vectorEffect.coffee removeSelf (#27): " + "delete");
    }
  });

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.VectorEffect = VectorEffect;

}).call(this);

//# sourceMappingURL=vectorEffect.js.map
