// Generated by CoffeeScript 1.9.2
(function() {
  var Button, WelcomeLayer, root,
    slice = [].slice;

  Button = cc.MenuItemImage.extend({
    doEffect: null,
    ctor: function(normal) {
      var that;
      that = this;
      this._super(normal, normal, function() {
        return that.onTouchBegan();
      }, this);
      return that = this;
    },
    onTouchBegan: function() {
      var that;
      that = this;
      this.stopAllActions();
      return this.runAction(cc.sequence(cc.scaleTo(0.3, 1.2).easing(cc.easeElasticOut()), cc.blink(0.5, 2), cc.callFunc(function() {
        return typeof that.doEffect === "function" ? that.doEffect() : void 0;
      }, that), cc.scaleTo(0.3, 1).easing(cc.easeElasticOut())));
    }
  });

  WelcomeLayer = cc.Layer.extend({
    _loadRes: function() {
      cc.spriteFrameCache.addSpriteFrames(res.res_plist);
      return cc.textureCache.addImage(res.res_png);
    },
    ctor: function() {
      var button1, button2, i, logo, menu, n, size, t, that;
      this._super();
      that = this;
      this._loadRes();
      size = cc.winSize;
      this.attr({
        x: size.width / 2,
        y: size.height / 2
      });
      logo = new cc.Sprite("#all/logo.png");
      logo.attr({
        y: size.height * 0.118,
        scale: 0.5,
        opacity: 0
      });
      this.addChild(logo, 10);
      button1 = new Button("#all/start.png");
      button1.attr({
        y: size.height * -0.118
      });
      button1.doEffect = function() {
        return myDirector.battle();
      };
      button2 = new Button("#all/select.png");
      button2.attr({
        y: button1.y - button2.height * 1.618
      });
      button2.doEffect = function() {
        return alert('此处正在施工，|++++++++|o(￣ヘ￣o＃)');
      };
      menu = new cc.Menu([button1, button2]);
      menu.attr({
        x: 0,
        y: 0
      });
      this.addChild(menu, 10);
      this.shake(logo, cc.rotateTo, 2.5, [6], [-6], cc.easeSineInOut());
      logo.runAction(cc.sequence(cc.delayTime(0.8), cc.fadeIn(1), cc.callFunc(function() {
        return that.shake(logo, cc.scaleTo, 2.5, [0.52], [0.5], cc.easeSineInOut());
      }, that)));
      button1.setOpacity(0);
      button2.setOpacity(0);
      button1.runAction(cc.sequence(cc.delayTime(1), cc.fadeIn(1)));
      button2.runAction(cc.sequence(cc.delayTime(1.3), cc.fadeIn(1)));
      for (n = i = 1; i <= 5; n = ++i) {
        this.createBackGround(n);
      }
      return t = new ccui.Button();
    },
    shake: function(target, act, time, max, min, ease) {
      if (ease == null) {
        ease = null;
      }
      return target.runAction(cc.repeatForever(cc.sequence(ease != null ? act.apply(null, [time].concat(slice.call(max))).easing(ease) : act.apply(null, [time].concat(slice.call(max))), ease != null ? act.apply(null, [time].concat(slice.call(min))).easing(ease) : act.apply(null, [time].concat(slice.call(min))))));
    },
    createBackGround: function(n) {
      var f, layer0, layer1, t;
      layer0 = new cc.Sprite("#backGround/welcome/" + n + ".png");
      this.addChild(layer0, n);
      layer0.setScale(2.003);
      layer0.getTexture().setAliasTexParameters();
      layer1 = new cc.Sprite("#backGround/welcome/" + n + ".png");
      this.addChild(layer1, n);
      layer1.attr({
        scale: 2.004,
        x: layer1.width * 2
      });
      layer1.getTexture().setAliasTexParameters();
      t = [0.2, 0.5, 0.9, 2, 4][n - 1];
      f = function() {
        this.x = this.x - t;
        if (this.x < -this.width * 2) {
          return this.x = this.x + this.width * 4;
        }
      };
      layer0.schedule(f, 0.05, cc.REPEAT_FOREVER);
      layer1.schedule(f, 0.05, cc.REPEAT_FOREVER);
      if (n === 1) {
        layer0.setX = -20;
        layer1.setX = -20;
        this.shake(layer0, cc.moveBy, 6, [0, 20], [0, -20], cc.easeSineInOut());
        return this.shake(layer1, cc.moveBy, 6, [0, 20], [0, -20], cc.easeSineInOut());
      }
    }
  });

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.WelcomeLayer = WelcomeLayer;

}).call(this);

//# sourceMappingURL=welcomeLayer.js.map
