// Generated by CoffeeScript 1.9.2
(function() {
  var TimerLayer, root;

  TimerLayer = cc.Layer.extend({
    ctor: function() {
      var size, that;
      this._super();
      size = cc.winSize;
      that = this;
      this.tc = 0;
      this.schedule(function() {
        return that.tc += 1;
      }, 1, cc.REPEAT_FOREVER, 2);
      this.schedule(this.timeCallBack, 1, 10, 1);
      return this.scheduleOnce(this.timeCallBackOnce, 10);
    },
    timeCallBack: function() {
      return cc.log('timeCallBack');
    },
    timeCallBackOnce: function() {
      return cc.log('timeCallbackOnce');
    },
    update: function(dt) {
      return cc.log('update');
    }
  });

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.TimerLayer = TimerLayer;

}).call(this);

//# sourceMappingURL=TimerLayer.js.map
